### ISSUE TITLE
error in convert submission on kvuc

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/fileconverter_flasksoffice#11]
On kvuc
adhoc task (\assignfeedback_editpdf\task\convert_submission) currently fails with the following. I dont know if this issues is a flaskoffice issue or a core issue - feel free to move repo if needed

![Image](https://github.com/praxisdigital/fileconverter_flasksoffice/assets/42199572/bf373430-9813-47e0-9d7e-7dba44214576)

**Comment by sampraxis** [comment]
@Mikkeljeppesen1 
The issue seem to be that the submitted files in the assignment submission are no longer in the moodle (got deleted)
I remove the tasks that have the issue.

I close the issue for now.
