### ISSUE TITLE
Update flask converter server url

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/fileconverter_flasksoffice#6]
When we're done testing the new flask converter deployment on mit.kvuc.dk, we need to change the server url setting in the upgrade script.

**New url:**
https://flask-soffice.moxis.dk/
```[tasklist]
### Tasks
- [ ] https://github.com/praxisdigital/drift/issues/163
```

**Comment by frederikmillingpytlick** [comment]
Awaiting test on mit.kvuc.dk

**Comment by mcardle** [comment]
- Certificate is not renewed automatically.
- Packages are not updated automatically - e.g. curl.

**Comment by frederikmillingpytlick** [comment]
This has been fixed in drift by hardcoding the setting in `settings.php`, closing issue
