### ISSUE TITLE
Error on KVUC  conversion failed

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/fileconverter_flasksoffice#7]
KVUC writes they get this errror whan using "Anmærk PDF" as feedback
https://mit.kvuc.dk/mod/assign/view.php?id=726356&rownum=0&action=grader&userid=3687#

![Image](https://github.com/praxisdigital/fileconverter_flasksoffice/assets/1931926/d85194c5-9aa3-4a53-b4f8-7b047698a9c4)

They have disabled the feedback option in the assisngment, and now i only get this error :

![Image](https://github.com/praxisdigital/fileconverter_flasksoffice/assets/1931926/0eee72eb-d0c5-4a87-8d5d-51907df58518)

I have testet here on Bos test course: https://mit.kvuc.dk/course/view.php?id=9727 and there are some test assignments and they seems to be working in the conversion, of files. I made a new assignment and uploaded an new word file, and the conversion of this failed as well. So it might only be new fil uploads in assignments that fails conversion.

They have the newest version installed. 

Hubspot: https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2263137269

**Comment by frederikmillingpytlick** [comment]
Same issue is happening on mitnielsbrock, when converting in the background. (adhoc tasks)

![Image](https://github.com/praxisdigital/fileconverter_flasksoffice/assets/78727001/1ae14c12-caa0-4fea-9fdd-02921bf4b158)

**Comment by frederikmillingpytlick** [comment]
@neeesn seems to work now :)
